node {
    stage('git checkout') {
        git credentialsId: 'git-cred', url: 'https://github.com/saumya2730/devopsfinal.git'
    }
    
    stage('code build & test') {
        //sh 'mvn clean package'
        def maven_home = tool name: 'maven-3', type: 'maven'
        def maven_cmd = "${maven_home}/bin/mvn"
        sh "${maven_cmd} clean package"
    }
    
    stage('docker build') {
        def dockerHome = tool name: 'Docker'
        def dockerCMD = "${dockerHome}/usr/local/bin/docker"
        sh "${dockerCMD} build -t saumya2730/devops-test:1.0 ."
    }
    
    stage('run') {
        def dockerHome = tool name: 'Docker'
        def dockerCMD = "${dockerHome}/usr/local/bin/docker"
        sh "${dockerCMD} run -p 8888:8080 -d saumya2730/devops-test:1.0"
    }
    
    stage('docker push') {
        def dockerHome = tool name: 'Docker'
        def dockerCMD = "${dockerHome}/usr/local/bin/docker"
        withCredentials([string(credentialsId: 'creds', variable: 'docker_password')]) {
            sh "${dockerCMD} login -u saumya2730 -p ${docker_password}"
            }
        sh "${dockerCMD} push saumya2730/devops-test:1.0"
    }
    
     stage('push to pcf') {
     
   
    withCredentials([usernamePassword(credentialsId: 'pcf_id', passwordVariable: 'pass', usernameVariable: 'user')]) {
    // some block
    sh '/usr/local/bin/cf login -u saumya.saxena2730@gmail.com -p ${pass} -o test-project-devops'
    }    
    sh '/usr/local/bin/cf push docker-img1 --docker-image saumya270/devops-test:1.0 --no-start'
}
     
}
