FROM openjdk:8-jdk-alpine

EXPOSE 8080

ARG JAR_FILE=/target/*.jar

COPY ${JAR_FILE} app.jar

RUN echo "Creation of your docker image is in progress"

MAINTAINER "learner2730@gmail.com"

ENTRYPOINT ["java", "-jar", "app.jar"]

